name: Influencer Dashboard

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1" # 3am every Monday

jobs:
  run-etl:
    runs-on: ubuntu-latest
    env:
      FB_TOKEN: ${{ secrets.fb_token }}
      APP_IG: ${{ secrets.app_id }}
      APP_SECRET: ${{ secrets.app_secret }}
      IG_BUSINESS_ID: ${{ secrets.ig_business_id }}
      USERNAME: ${{ secrets.username }}
      PORT: ${{ secrets.port }}
      PWD: ${{ secrets.pwd }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt       

      - name: Run pipeline
        run: python main.py

      - name: Check for file changes
        run: |
          git config user.name github-actions
          git config user.email githubaction@github.com
          git add .
          git diff --staged --quiet || echo "change=true" >> $GITHUB_ENV

      - name: Commit & push if changed
        if: env.change == 'true'
        run: |
          git commit -m "Auto: Updated ETL output"
          git push
