name: Agent-search

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * 1" # every Monday at 01:00 am  UTC

permissions:
  contents: write

jobs:
  run-agent-search:
    runs-on: ubuntu-latest
    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      CSE_KEY: ${{ secrets.CSE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --no-cache-dir

      - name: Run Agent
        run: python sh.py

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Check for file changes
        id: git_diff
        run: |
          git add .
          if ! git diff --staged --quiet; then
            echo "changed=true" >> $GITHUB_ENV
          fi

      - name: Commit & push if changed
        if: env.changed == 'true'
        run: |
          git commit -m "Auto: Updated ETL output"
          git push
