name: Tiktok Influencers

on:
  push:
  schedule:
    - cron: "0 3 * * *"

permissions:
  contents: write

jobs:
  run-tik-pipeline:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --no-cache-dir
          playwright install

      - name: Run pipeline
        run: python tik.py

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Check for file changes
        id: git_diff
        run: |
          git add .
          if ! git diff --staged --quiet; then
            echo "changed=true" >> $GITHUB_ENV
          fi

      - name: Commit & push if changed
        if: env.changed == 'true'
        run: |
          git commit -m "Auto: Updated ETL output"
          git push
